version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    env_file:
      - hadoop.env
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    ports:
      - "9864:9864"

volumes:
  hadoop_namenode:
  hadoop_datanode:
